### ISSUE TITLE
The tab exceeds the tabbar width when too many files are opened

### ISSUE THREAD

**Issue by Sdky** [gatziourasd/typora-tabbar-plugin#1]
Hey, thanks for the plugin. I found that when too many files are opened, the tab will exceed the width of the tabbar. Is it possible to fix it?

![image](https://user-images.githubusercontent.com/29597396/157279751-1e073fd3-4f27-4391-add5-d32a45d40b0a.png)

**Comment by gatziourasd** [comment]
Just fixed it.
You can now scroll the tabbar.

[Typora TabBar Plugin v0.2.0](https://github.com/gatziourasd/typora-tabbar-plugin/releases/tag/v0.2.0)


https://user-images.githubusercontent.com/41538138/157713042-817b7be7-e7d2-41fc-896f-d17854aeca15.mp4
