### ISSUE TITLE
Cannot open a new tab from search results

### ISSUE THREAD

**Issue by Sdky** [gatziourasd/typora-tabbar-plugin#2]
Cannot open a new tab from search results. Is it possible to fix it?
Thanks :)

https://user-images.githubusercontent.com/29597396/157719450-7663786e-8b55-4562-9045-a87f90e31c23.mp4

**Comment by gatziourasd** [comment]
Tabs can now be opened directly from the search view.

[Typora TabBar Plugin v0.3.0](https://github.com/gatziourasd/typora-tabbar-plugin/releases/tag/v0.3.0)

https://user-images.githubusercontent.com/41538138/157755331-79596d7f-ace9-4542-b81b-2d06b22191de.mp4
