### ISSUE TITLE
Cant not remember the position of the document after switching tabs

### ISSUE THREAD

**Issue by Sdky** [gatziourasd/typora-tabbar-plugin#3]
When I switch to another tabs and then switch back to the previous tab, it will automatically scroll to the top of the document. 
Can it remember the position of the document after switching tabs? Thanks.

https://user-images.githubusercontent.com/29597396/157907715-cdc04102-d611-475b-af2b-efde1b07134c.mp4

**Comment by gatziourasd** [comment]
This seems to be a bug directly in Typora, as it’s still prevalent without the plugin.

When switching between two files Typora will remember the scroll position, but as soon as you switch between more than two files it will always open the document scrolled to the top.

https://user-images.githubusercontent.com/41538138/158016257-174d63f7-8695-4597-ad4b-cf14810d69ff.mp4


There is also an old open issue here: https://github.com/typora/typora-issues/issues/1955.

**Comment by gatziourasd** [comment]
I am unsure if it would be better to fix this in the plugin or open a new issue on the Typora-Issues repo.

**Comment by Sdky** [comment]
> I am unsure if it would be better to fix this in the plugin or open a new issue on the Typora-Issues repo.

I don't think it will be fixed on Typora, because this issue has been open for more than three years. 😞

**Comment by gatziourasd** [comment]
Tabs now keep track of the document's scroll position and scroll the document to the correct position when switching tabs.

[Typora TabBar Plugin v0.4.0](https://github.com/gatziourasd/typora-tabbar-plugin/releases/tag/v0.4.0)

https://user-images.githubusercontent.com/41538138/158029218-0e2c7b23-40ff-45bf-90ce-28ddf2dd2582.mp4
