### ISSUE TITLE
The problem with scrolling

### ISSUE THREAD

**Issue by elohim4eg** [gatziourasd/typora-tabbar-plugin#4]
Hello.
I found a strange problem of not being able to scroll the document with the mouse arrow
I attach a short video to make it clearer
Sorry about the quality.
As you can see, scrolling with the mouse wheel works, but dragging the arrow does not work

https://user-images.githubusercontent.com/105471224/168200106-d837dcca-aef8-4d92-a648-7768b6f6dc50.mp4

**Comment by gatziourasd** [comment]
It's fixed now.
You can scroll the document with the scrollbar again.

Thanks for reporting.

[Typora TabBar Plugin v0.4.1](https://github.com/gatziourasd/typora-tabbar-plugin/releases/tag/v0.4.1)
