### ISSUE TITLE
Not working on Typora 1.3.8 version

### ISSUE THREAD

**Issue by weey007** [gatziourasd/typora-tabbar-plugin#5]
After I upgraded Typora to 1.3.8 today, I found that this plugin doesn't work anymore

![image](https://user-images.githubusercontent.com/2442046/182107669-e35e7a6b-ad02-4cae-b5c7-972208a7375a.png)

**Comment by gatziourasd** [comment]
Thanks for reporting! 

It seems like Typora changed the path to the `typora://userData` Folder to `typora://app/userData/[...]`

It works for me again, if I change the paths in the `<typora-installation-path>/resources/window.html` to:
```
<script src="typora://app/userData/plugins/tabbar/bundle.js" defer></script>
<link rel="stylesheet" href="typora://app/userData/plugins/tabbar/bundle.css">
```
---
Would you try this for me on your machine?

If that works I'll update the docs.

**Comment by weey007** [comment]
> Thanks for reporting!
> 
> It seems like Typora changed the path to the `typora://userData` Folder to `typora://app/userData/[...]`
> 
> It works for me again, if I change the paths in the `<typora-installation-path>/resources/window.html` to:
> 
> ```
> <script src="typora://app/userData/plugins/tabbar/bundle.js" defer></script>
> <link rel="stylesheet" href="typora://app/userData/plugins/tabbar/bundle.css">
> ```
> 
> Would you try this for me on your machine?
> 
> If that works I'll update the docs.

Yes, after I modified the path, the plugin works normally, thank you very much
